#!/bin/sh

[ -d $1 ] || exit 1

NAME=$1

if [ -f $NAME/recoverytool.config ] ; then 
    rm -f $NAME/recoverytool.txt
    grep SoftwareUpdateSite $NAME/recoverytool.config > $NAME/recoverytool.txt
    for hash in `grep Approval $NAME/recoverytool.config` ; do \
	printf "$hash\n" >> $NAME/recoverytool.txt ; \
	printf "$hash" | sed -e 's/=.*$//' | tr -d '\n' >> $NAME/recoverytool.txt ; \
	printf '=' >> $NAME/recoverytool.txt ; \
	printf "$hash" | sed -e 's/^[^=]*=//' | openssl enc -d -a -A | \
	tar -z -t -f - | tr -d '\n' >> $NAME/recoverytool.txt ; \
	printf " '" >> $NAME/recoverytool.txt ; \
	printf "$hash" | sed -e 's/^[^=]*=//' | openssl enc -d -a -A | \
	tar -z -x -O -f - | tr -d '\n' >> $NAME/recoverytool.txt ; \
	printf "'\n" >> $NAME/recoverytool.txt ; \
    done
fi
